const fs=require('node:fs/promises');
const path=require('node:path');
const assert=require('node:assert/strict');
const origin='http://127.0.0.1:4174';
const wait=ms=>new Promise(r=>setTimeout(r,ms));
async function main(){
  const targets=await(await fetch('http://127.0.0.1:9223/json')).json();
  const target=targets.find(t=>t.type==='page'&&(t.url==='about:blank'||t.url.startsWith(origin)));
  if(!target)throw new Error('Open a blank headless Chrome target on port 9223.');
  const ws=new WebSocket(target.webSocketDebuggerUrl);await new Promise(r=>ws.addEventListener('open',r,{once:true}));
  let seq=0;const pending=new Map(),errors=[],requests=[];
  ws.addEventListener('message',e=>{const m=JSON.parse(e.data);if(m.id){const p=pending.get(m.id);pending.delete(m.id);m.error?p.reject(m.error):p.resolve(m.result);}else if(m.method==='Runtime.exceptionThrown')errors.push(m.params.exceptionDetails);else if(m.method==='Network.requestWillBeSent')requests.push({url:m.params.request.url,method:m.params.request.method});});
  const cdp=(method,params={})=>new Promise((resolve,reject)=>{const id=++seq;pending.set(id,{resolve,reject});ws.send(JSON.stringify({id,method,params}));});
  const ev=async expression=>{const r=await cdp('Runtime.evaluate',{expression,awaitPromise:true,returnByValue:true});if(r.exceptionDetails)throw new Error(JSON.stringify(r.exceptionDetails));return r.result.value;};
  async function until(expr){for(let i=0;i<100;i++){if(await ev(expr))return;await wait(100);}throw new Error('Timed out: '+expr);}
  const click=selector=>ev(`document.querySelector(${JSON.stringify(selector)}).click()`);
  const change=(selector,value)=>ev(`{const e=document.querySelector(${JSON.stringify(selector)});e.value=${JSON.stringify(value)};e.dispatchEvent(new Event('input',{bubbles:true}));e.dispatchEvent(new Event('change',{bubbles:true}));}`);
  const reset=async scenario=>{const r=await fetch(origin+'/__experiment/scenario',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({scenario})});assert.equal(r.status,200);};
  const navigate=async page=>{await cdp('Page.navigate',{url:origin+'/'+page});await until('document.readyState === "complete" && typeof UI !== "undefined"');};
  await fs.mkdir(path.join(__dirname,'.qa'),{recursive:true});
  async function shot(name){const result=await cdp('Page.captureScreenshot',{format:'png',captureBeyondViewport:false});await fs.writeFile(path.join(__dirname,'.qa',name+'.png'),Buffer.from(result.data,'base64'));}
  await cdp('Runtime.enable');await cdp('Page.enable');await cdp('Network.enable');
  await cdp('Emulation.setDeviceMetricsOverride',{width:2559,height:1399,deviceScaleFactor:1,mobile:false});
  await reset('mixed');await navigate('');await ev('localStorage.setItem("tectrace-live","false")');
  await until('document.querySelectorAll("#recordings-body tr").length===24');
  assert(!requests.some(r=>r.url.endsWith('/catalog/rescan')),'No implicit scan');
  await shot('recordings-2k');
  console.log('Geometry',await ev('JSON.stringify({root:getComputedStyle(document.documentElement).fontSize,toolbar:document.querySelector(".topbar").getBoundingClientRect().height,folder:document.querySelector(".project-panel").getBoundingClientRect().width,overflow:document.documentElement.scrollWidth>innerWidth})'));
  await click('.folders-toggle');assert(await ev('document.querySelector(".workspace").classList.contains("folders-hidden")'));
  await click('.folders-rail-toggle');
  await ev('[...document.querySelectorAll(".folder-select")].find(b=>b.textContent.includes("Inbox")).click()');
  assert.equal(await ev('document.querySelectorAll("#recordings-body tr").length'),8);
  await ev('[...document.querySelectorAll(".folder-select")].find(b=>b.textContent.includes("All recordings")).click()');
  await change('#recording-search','Precision');assert.equal(await ev('document.querySelectorAll("#recordings-body tr").length'),1);assert.equal(await ev('document.querySelectorAll("#recordings-body test").length'),0);
  await click('#reset-filters');await change('#health-filter','damaged');assert.equal(await ev('document.querySelectorAll("#recordings-body tr").length'),1);assert(await ev('document.querySelector("#recordings-body input").disabled'));
  await click('#reset-filters');await change('#recording-search','Unprepared run');await click('#recordings-body input');await click('#prepare-selected');
  await until('!!document.querySelector("dialog[open]")');await shot('prepare-dialog-2k');
  await ev('[...document.querySelectorAll("dialog button")].find(b=>b.textContent==="Prepare").click()');await until('!document.querySelector("dialog")');
  const overview=await(await fetch(origin+'/api/v1/processing/overview')).json();assert(overview.queue.some(j=>j.recording_id===2));
  await reset('mixed');await navigate('processing.html');await until('document.querySelector(".job-name").textContent.includes("Processing run")');
  await click('#pause-job');await until('document.querySelector("#pause-job").getAttribute("aria-label")==="Resume processing"');
  await shot('processing-2k');
  await click('#jobs-body tr:last-child input');await ev('[...document.querySelectorAll(".jobs-actions button")].find(b=>b.textContent==="Move earlier").click()');await until('document.querySelector("#jobs-body tr").textContent.includes("IMU bundle")');
  await click('#jobs-body tr:first-child input');await ev('[...document.querySelectorAll(".jobs-actions button")].find(b=>b.textContent==="Move later").click()');await until('document.querySelector("#jobs-body tr").textContent.includes("Top camera")');
  await click('#jobs-body tr:first-child input');await ev('[...document.querySelectorAll(".jobs-actions button")].find(b=>b.textContent==="Cancel selected").click()');await until('document.querySelectorAll("#jobs-body tr").length===1');await click('#pause-job');await until('document.querySelector("#pause-job").getAttribute("aria-label")==="Pause processing"');
  await click('#cancel-job');await until('!document.querySelector(".job-name").textContent.includes("Front camera")');
  await click('#failures-tab');await until('document.querySelector("#jobs-body").textContent.includes("Failed camera")');
  await click('#jobs-body input');await ev('[...document.querySelectorAll(".jobs-actions button")].find(b=>b.textContent==="Retry selected").click()');await until('document.querySelector("#jobs-body").textContent.includes("No failed jobs")');
  await click('#history-tab');await until('document.querySelector("#jobs-body").textContent.includes("Figure eight")');
  await click('#canceled-tab');await until('document.querySelector("#jobs-body").textContent.includes("Processing run")');
  await navigate('analyzer.html?id=1');await until('document.querySelectorAll("#graph-metric option").length===6');await until('[...document.querySelectorAll("video")].every(v=>v.readyState>=2)');
  await until('!document.querySelector("#imu-graph").hidden && document.querySelector("#imu-graph").height>100');assert.equal(await ev('document.querySelectorAll(".analyzer-workspace>.details-section").length'),0);await shot('analyzer-2k');
  await click('#graph-play');await wait(600);await click('#graph-play');assert((await ev('Number(document.querySelector(".timeline input").value)'))>.1);
  await change('.timeline input','5');await wait(500);console.log('Media seek',await ev('[...document.querySelectorAll("video")].map(v=>({time:v.currentTime,hidden:v.hidden,ready:v.readyState}))'));
  assert(await ev('[...document.querySelectorAll("video")].every(v=>Math.abs(v.currentTime-5)<.11)'));
  await change('#graph-metric','linear_acceleration_z');await click('#graph-zoom-in');await click('#graph-reset');
  await click('.details-toggle');assert(await ev('document.querySelector("#recording-details").hidden'));await click('.details-toggle');
  await click('[aria-label="Graph help"]');await until('!!document.querySelector("dialog[open]")');await ev('document.querySelector("dialog").close()');
  await navigate('analyzer.html?id=8');await until('document.querySelectorAll("#graph-metric option").length===6');assert(await ev('[...document.querySelectorAll("video")].every(v=>v.hidden)'));
  await change('.timeline input','5');await wait(400);assert(await ev('[...document.querySelectorAll("video")].every(v=>!v.hidden)'));
  await change('.timeline input','15');assert(await ev('[...document.querySelectorAll("video")].every(v=>v.hidden)'));
  await navigate('analyzer.html?id=7');await until('document.querySelectorAll("#graph-metric option").length===6');assert(await ev('document.querySelector("#graph-play").disabled'));
  await navigate('analyzer.html?id=5');await until('document.querySelectorAll("#graph-metric option").length===6');assert.equal(await ev('document.querySelectorAll("video").length'),1);
  await cdp('Emulation.setDeviceMetricsOverride',{width:1440,height:900,deviceScaleFactor:1,mobile:false});
  for(const page of ['', 'processing.html','analyzer.html?id=1']){await navigate(page);await wait(800);await shot((page.startsWith('analyzer')?'analyzer':page?'processing':'recordings')+'-laptop');assert(await ev('document.documentElement.scrollWidth===innerWidth'));}
  await reset('scan-error');await navigate('');await until('document.querySelectorAll("#recordings-body tr").length===24');await click('#scan-retry');await until('document.querySelector(".api-notice").textContent.includes("previous catalog")');assert.equal(await ev('document.querySelectorAll("#recordings-body tr").length'),24);
  await reset('empty');await navigate('');await until('!document.querySelector("#recordings-empty").hidden');assert.equal(await ev('document.querySelectorAll("#recordings-body tr").length'),0);
  await reset('api-error');await navigate('');await until('document.querySelector(".api-notice").textContent.includes("unavailable")');
  await click('.app-settings');await until('!!document.querySelector(".scenario-choices")');await shot('settings-laptop');
  await ev('[...document.querySelectorAll(".scenario-choices button")].find(b=>b.textContent==="mixed").click()');await until('document.readyState==="complete" && document.querySelectorAll("#recordings-body tr").length===24');
  assert.equal(errors.length,0,JSON.stringify(errors));
  await fs.writeFile(path.join(__dirname,'.qa','browser-report.json'),JSON.stringify({passed:true,errors,requests},null,2));
  console.log('Browser flow passed; screenshots saved in .qa.');ws.close();
}
main().catch(e=>{console.error(e);process.exit(1);});
