CREATE TABLE IF NOT EXISTS recordings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    archive_relative_path TEXT NOT NULL UNIQUE,
    display_name TEXT NOT NULL,
    start_time_ns BIGINT,
    duration_ns BIGINT CHECK (duration_ns IS NULL OR duration_ns >= 0),
    total_source_size_bytes BIGINT CHECK (
        total_source_size_bytes IS NULL OR total_source_size_bytes >= 0
    ),
    storage_format TEXT,
    metadata_version INTEGER CHECK (
        metadata_version IS NULL OR metadata_version >= 0
    ),
    message_count BIGINT CHECK (message_count IS NULL OR message_count >= 0),
    topic_count INTEGER CHECK (topic_count IS NULL OR topic_count >= 0),
    ros_health TEXT NOT NULL CHECK (
        ros_health IN (
            'readable', 'damaged', 'missing', 'unsupported', 'uninspectable'
        )
    ),
    diagnostic_code TEXT,
    diagnostic_message TEXT CHECK (
        diagnostic_message IS NULL OR char_length(diagnostic_message) <= 500
    ),
    source_revision TEXT NOT NULL CHECK (char_length(source_revision) = 64),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CHECK (archive_relative_path <> ''),
    CHECK (display_name <> '')
);

CREATE TABLE IF NOT EXISTS source_components (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recording_id BIGINT NOT NULL REFERENCES recordings(id) ON DELETE CASCADE,
    role TEXT NOT NULL CHECK (
        role IN (
            'metadata', 'ros_database', 'topdown_video', 'topdown_timestamps'
        )
    ),
    relative_path TEXT,
    size_bytes BIGINT CHECK (size_bytes IS NULL OR size_bytes >= 0),
    mtime_ns BIGINT,
    condition TEXT NOT NULL CHECK (
        condition IN (
            'present', 'readable', 'missing', 'ambiguous', 'invalid',
            'unsupported', 'damaged', 'uninspectable'
        )
    ),
    diagnostic_code TEXT,
    diagnostic_message TEXT CHECK (
        diagnostic_message IS NULL OR char_length(diagnostic_message) <= 500
    ),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (recording_id, role),
    CHECK (relative_path IS NULL OR relative_path <> '')
);
