CREATE TABLE IF NOT EXISTS artifacts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recording_id BIGINT NOT NULL REFERENCES recordings(id) ON DELETE CASCADE,
    kind TEXT NOT NULL CHECK (kind = 'front_preview'),
    cache_identity TEXT NOT NULL CHECK (char_length(cache_identity) = 64),
    output_relative_path TEXT NOT NULL CHECK (output_relative_path <> ''),
    mime_type TEXT NOT NULL CHECK (mime_type <> ''),
    size_bytes BIGINT NOT NULL CHECK (size_bytes > 0),
    coverage_start_ns BIGINT NOT NULL,
    coverage_end_ns BIGINT NOT NULL,
    manifest JSONB NOT NULL CHECK (jsonb_typeof(manifest) = 'object'),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (kind, cache_identity),
    CHECK (coverage_end_ns >= coverage_start_ns)
);

CREATE TABLE IF NOT EXISTS jobs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recording_id BIGINT NOT NULL REFERENCES recordings(id) ON DELETE CASCADE,
    kind TEXT NOT NULL CHECK (kind = 'front_preview'),
    cache_identity TEXT NOT NULL CHECK (char_length(cache_identity) = 64),
    state TEXT NOT NULL CHECK (
        state IN ('queued', 'running', 'succeeded', 'failed')
    ),
    queued_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    started_at TIMESTAMPTZ,
    finished_at TIMESTAMPTZ,
    error_code TEXT,
    error_message TEXT CHECK (
        error_message IS NULL OR char_length(error_message) <= 500
    ),
    CHECK (
        (state = 'queued' AND started_at IS NULL AND finished_at IS NULL)
        OR (state = 'running' AND started_at IS NOT NULL AND finished_at IS NULL)
        OR (
            state IN ('succeeded', 'failed')
            AND started_at IS NOT NULL
            AND finished_at IS NOT NULL
        )
    ),
    CHECK (
        (state = 'failed' AND error_code IS NOT NULL AND error_message IS NOT NULL)
        OR (state <> 'failed' AND error_code IS NULL AND error_message IS NULL)
    )
);

CREATE UNIQUE INDEX IF NOT EXISTS jobs_one_active_identity
    ON jobs (kind, cache_identity)
    WHERE state IN ('queued', 'running');

CREATE INDEX IF NOT EXISTS jobs_queue_order
    ON jobs (queued_at, id)
    WHERE state = 'queued';
